server:
  port: ${SERVER_PORT:19000}
spring:
  application:
    name: mcp-server-provider

  cloud:
    # nacos注册中心配置
    nacos:
#      discovery:
#        username: nacos
#        password: nacos
#        server-addr: 127.0.0.1:8848
      restful-services:
        - mcp-restful-provider
#        - mcp-restful-second-provider

management:
  endpoints:
    web:
      exposure:
        exclude: "*"

---
spring:
  main:
    banner-mode: off
  ai:
    mcp:
      server:
        name: mcp-server-provider
        version: 1.0.1
#        sse-message-endpoint: /mcp/messages
        type: SYNC
    alibaba:
      mcp:
        nacos:
          enabled: true
          server-addr: 127.0.0.1:8848
          username: nacos
          password: nacos
          registry:
            enabled: true
            service-namespace: 9ba5f1aa-b37d-493b-9057-72918a40ef35
            service-group: mcp-server

# 调试日志
logging:
  level:
    io:
      modelcontextprotocol:
        client: DEBUG
        spec: DEBUG
        server: DEBUG