server:
  port: 8080

spring:
  application:
    name: mcp-client-webflux
#  main:
#    web-application-type: none
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}

    mcp:
      client:
        sse:
          connections:
            server1:
              url: http://localhost:18090
              headers-map:
                token-yingzi: yingzi
            server2:
              url: http://localhost:18091
              headers-map:
                token-yingzi-2: yingzi2

# 调试日志
logging:
  level:
    io:
      modelcontextprotocol:
        client: DEBUG
        spec: DEBUG