server:
  port: 8080

spring:
  application:
    name: mcp-client-webflux
  main:
    web-application-type: none
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}

    mcp:
      client:
        sse:
          connections:
            server1:
              url: http://localhost:18085
              headers-map:
                token-yingzi: yingzi
                token-yingzi-2: yingzi-2
                token-yingzi-3: yingzi-3

# 调试日志
logging:
  level:
    io:
      modelcontextprotocol:
        client: DEBUG
        spec: DEBUG