server:
  port: 8080

spring:
  application:
    name: mcp-client-webflux
#  main:
#    web-application-type: none
  ai:
#    dashscope:
#      api-key: ${DASHSCOPE_API_KEY}
    openai:
      api-key: ${DASHSCOPE_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen-max

    alibaba:
      mcp:
        nacos:
          enabled: true
          service-namespace: 9ba5f1aa-b37d-493b-9057-72918a40ef35
          server-addr: 127.0.0.1:8848
          username: nacos
          password: nacos

        client:
          sse:
            connections:
              server1: mcp-server-provider
#              mcp-server-provider-mcp-service:
#                service-name: mcp-server-provider-mcp-service
#                group: mcp-server
#                data-id: mcp-server-provider-mcp-server.json
    mcp:
      client:
        enabled: true
        name: mcp-client-webflux
        version: 0.0.1
        initialized: true
        request-timeout: 600s

        nacos-enabled: true

        type: sync
        toolcallback:
          enabled: true
        root-change-notification: true

#        sse:
#          connections:
#            server1:
#              url: http://localhost:19000
#              headers-map:
#                token-yingzi: yingzi
  #            server2:
#              url: http://localhost:19100
#              headers-map:
#                token-yingzi-2: yingzi2



#  cloud:
#    # nacos注册中心配置
#    nacos:
#      discovery:
#        username: nacos
#        password: nacos
#        server-addr: 127.0.0.1:8848

# 调试日志
logging:
  level:
    io:
      modelcontextprotocol:
        client: DEBUG
        spec: DEBUG