server:
  port: 18091
spring:
  application:
    name: service-gateway-second

  cloud:
    # nacos注册中心配置
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 127.0.0.1:8848
      restful-services:
        - mcp-restful-threed-provider

management:
  endpoints:
    web:
      exposure:
        exclude: "*"

---
spring:
  main:
    banner-mode: off
  ai:
    mcp:
      server:
        name: mcp-restful-provider-second
        version: 0.0.1

# 调试日志
logging:
  level:
    io:
      modelcontextprotocol:
        client: DEBUG
        spec: DEBUG